config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	resources :sections, param: :sectioncode do
		get "/sections", to: "sections#index"
		member do
			post :add_to_queue
		end
		resources :spaces, param: :spacecode do
			member do
				post :add_to_queue
			end
			resources :items, param: :itemcode do
				post :add_small_to_queue
				post :add_large_to_queue
			end
		end
	end

	get "/print", to: "print#index"

	resources :print_queue_items, only: [] do
		member do
			post :change_quantity
			delete :delete_item
		end
	end

	get 'print_shop', to: "print_shop#index" 
	get 'print_page', to: "print_shop#show" 
	get 'search', to: "search#index" 

	# Defines the root path route ("/")
	root :controller => 'static', :action => :index
end

app/models/space.rb
class Space < ApplicationRecord
	include HasBarcode
	include Searchable

	validates :spacecode,  allow_blank: false, presence: true, uniqueness: { scope: :sectioncode_id }
	validates_numericality_of :spacecode, :less_than_or_equal_to => 9999, :greater_than_or_equal_to => 1
	validates :name, length: {maximum: 50}, allow_blank: false, presence: true
	validates :description, length: {maximum: 100}, allow_blank: false, presence: true

	has_barcode :qr,
		:outputter => :svg,
		:type => :qr_code,
		:value => Proc.new { |s| "SHERLOCK;SECTIONCODE:#{s.sectioncode_id.to_s.rjust(4, '0')};SPACECODE:#{s.spacecode.to_s.rjust(4, '0')};;RESTOREDATA;NAME:#{(s.name + '*' * 50)[0,50]};DESCRIPTION:#{(s.description + '*' * 100)[0,100]};;" }

	belongs_to :section, foreign_key: :sectioncode_id, primary_key: :sectioncode, required: true
	has_many :items, foreign_key: :spacecode_actual_id, primary_key: :id, dependent: :destroy
	def to_param
		spacecode
	end

	after_commit :create_search_entry, on: :create
	after_commit :update_search_entry, on: :update
	after_commit :destroy_search_entry, on: :destroy

	private
		def create_search_entry
			SearchEntry.create(name: self.name, url: Rails.application.routes.url_helpers.section_space_path(self.sectioncode_id, self.spacecode), searchable: self)
		end

		def update_search_entry
			if self.search_entry.present?
				self.search_entry.update(name: self.name, url: Rails.application.routes.url_helpers.section_space_path(self.sectioncode_id, self.spacecode))
			else
				SearchEntry.create(name: self.name, url: Rails.application.routes.url_helpers.section_space_path(self.sectioncode_id, self.spacecode), searchable: self)
			end
		end

		def destroy_search_entry
			self.search_entry.destroy if self.search_entry.present?
		end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
	before_action :authenticate_user!
	def index
		@section = Section.find_by!(:sectioncode => params[:section_sectioncode])
		@spaces = Space.where(:sectioncode_id => params[:section_sectioncode])
	end
	def show
		@section = Section.find_by!(:sectioncode => params[:section_sectioncode])
		@space = Space.find_by!(:sectioncode_id => params[:section_sectioncode], :spacecode => params[:spacecode])
	end

	def new
		@section = Section.find_by!(:sectioncode => params[:section_sectioncode])
		@space = Space.new
	end
	
	def create
		@space = Space.new(space_params)
		@section = Section.find_by!(:sectioncode => params[:section_sectioncode])
		@space.sectioncode_id = params[:section_sectioncode]
		if @space.save
			redirect_to section_space_path(@space.sectioncode_id, @space.spacecode)
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@space = Space.find_by!(:sectioncode_id => params[:section_sectioncode], :spacecode => params[:spacecode])
		@section = Section.find_by!(:sectioncode => params[:section_sectioncode])
		@backpath = section_space_path(@space.sectioncode_id, @space.spacecode)
		@name = @space.name
	end
	
	def update
		@space = Space.find_by!(:sectioncode_id => params[:section_sectioncode], :spacecode => params[:spacecode])
		@section = Section.find_by!(:sectioncode => params[:section_sectioncode])
		@backpath = section_space_path(@space.sectioncode_id, @space.spacecode)
		@name = @space.name
		if @space.update(space_params)
			redirect_to section_space_path(@space.sectioncode_id, @space.spacecode)
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def add_to_queue
		@space = Space.find_by!(:sectioncode_id => params[:section_sectioncode], :spacecode => params[:spacecode])
		@section = Section.find_by!(:sectioncode => params[:section_sectioncode])

		printString = "Space Label for #{@space.name} of section #{@section.name}"
		if @current_queue.print_queue_items.find_by(:itemhash => Digest::SHA256.hexdigest(printString)) != nil
			printItem = @current_queue.print_queue_items.find_by(:itemhash => Digest::SHA256.hexdigest(printString))
			printItem.quantity += 1
			printItem.print_content = render("_label", locals: { space: @space }, :layout => false)
			printItem.save!
		else
			printItem = @current_queue.print_queue_items.new(:name => printString, :itemhash => Digest::SHA256.hexdigest(printString), :quantity => 1, :print_content => render("_label", locals: { space: @space }, :layout => false))
			printItem.save!
		end

		

		respond_to do |format|
			format.html
			format.js
		end
	end

	helper_method :add_to_queue

	def destroy
		@space = Space.find_by!(:sectioncode_id => params[:section_sectioncode], :spacecode => params[:spacecode])
		@space.destroy
	
		redirect_to section_spaces_path, status: :see_other
	end

	private
		def space_params
			params.require(:space).permit(:spacecode, :name, :description)
		end
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_form.html.erb
<%= form_with(model: @space, url: [@section, @space]) do |form| %>
     <div class="field">
          <%= form.label :spacecode, 'Space code' %><br />
          <% @space.errors.full_messages_for(:spacecode).each do |message| %>
               <div class="destructive"><b><%= message %></b></div>
          <% end %>
          <%= form.number_field :spacecode %>
     </div>
     <div class="field">
          <%= form.label :name %><br />
          <% @space.errors.full_messages_for(:name).each do |message| %>
               <div class="destructive"><b><%= message %></b></div>
          <% end %>
          <%= form.text_field :name %>
     </div>
     <div class="field">
          <%= form.label :description %><br />
          <% @space.errors.full_messages_for(:description).each do |message| %>
               <div class="destructive"><b><%= message %></b></div>
          <% end %>
          <%= form.text_area :description %>
     </div>
     <div class="actions">
          <%= form.submit %>
     </div>
<% end %>

app/views/spaces/edit.html.erb
<%= link_to '< Go back to "'+@name+'"', @backpath %>

<h1>Edit <i>"<%= @name %>"</i></h1>

<%= render "form", space: @space %>

app/views/spaces/index.html.erb
<%= link_to '< Go back to "'+@section.name+'"', section_path(@section.sectioncode) %>

<h1>Spaces under <i>"<%= @section.name %>"</i></h1>

<h2>Assigned Spaces</h2>

<% if @spaces.empty? %>
<p>You have not created any spaces under <i>"<%= @section.name %>"</i> yet. </p>
<% else %>
<table class="standard-table">
<tr>
    <th>Code</th>
    <th>Name</th> 
    <th>Description</th>
</tr>
<% @spaces.each do |space| %>
     <tr>
          <td><%= space.spacecode %></td>
          <td><%= link_to space.name, section_space_path(space.sectioncode_id, space.spacecode) %></td> 
          <td><%= space.description %></td>
     </tr>
<% end %>
</table>
<% end %>
<i><%= link_to "Create a new space", new_section_space_path %></i>

app/views/spaces/new.html.erb
<%= link_to '< See all spaces in "'+@section.name+'"', section_spaces_path %>
<h1>Create a New Space</i></h1>

<%= render "form", section: @section, space: @space %>

app/views/spaces/show.html.erb
<%= link_to '< See all spaces', section_spaces_path %>

<h1><%= @space.name %></h1>

<%= render "label", space: @space %>

<table class="open-table">
<tr>
     <th>Parameter</th><th>Value</th>
</tr>
<tr><td><i>Space Code</i></td><td><%= @space.spacecode %></td></tr>
<tr><td><i>Name</i></td><td><%= @space.name %></td></tr>
<tr><td><i>Description</i></td><td><%= @space.description %></td></tr>
<tr><td><i>Created at</i></td><td><%= @space.created_at %></td></tr>
<tr><td><i>Last updated at</i></td><td><%= @space.updated_at %></td></tr>

</table>
<i><%= link_to "Edit", edit_section_space_path %></i> | <i><%= link_to "View Items >", section_space_items_path(:space_spacecode => @space.spacecode) %></i>

<%= button_to "Add to print queue", add_to_queue_section_space_path(@section.sectioncode, @space.spacecode) %>

<h2 class="destructive">Delete this space</h2>
<p>If you no longer use this space, you can choose to delete it. All inventory items associated with this space will be destroyed. This action is irreversible.</p>

<%= button_to "I understand the consequences, delete this space", section_space_path, data: { turbo_confirm: "Are you sure you want to delete this space?\n\n This action is irreversible." }, method: :delete, class: "destructive-background" %>