config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	resources :sections, param: :sectioncode do
		get "/sections", to: "sections#index"
		member do
			post :add_to_queue
		end
		resources :spaces, param: :spacecode do
			member do
				post :add_to_queue
			end
			resources :items, param: :itemcode do
				post :add_small_to_queue
				post :add_large_to_queue
			end
		end
	end

	get "/print", to: "print#index"

	resources :print_queue_items, only: [] do
		member do
			post :change_quantity
			delete :delete_item
		end
	end

	get 'print_shop', to: "print_shop#index" 
	get 'print_page', to: "print_shop#show" 
	get 'search', to: "search#index" 

	# Defines the root path route ("/")
	root :controller => 'static', :action => :index
end

app/models/section.rb
class Section < ApplicationRecord
	include HasBarcode
	include Searchable

	validates :sectioncode,  allow_blank: false, presence: true, uniqueness: true
	validates_numericality_of :sectioncode, :less_than_or_equal_to => 9999, :greater_than_or_equal_to => 1
	validates :name, length: {maximum: 50}, allow_blank: false, presence: true
	validates :description, length: {maximum: 100}, allow_blank: false, presence: true

	has_barcode :qr,
		:outputter => :svg,
		:type => :qr_code,
		:value => Proc.new { |s| "SHERLOCK;SECTIONCODE:#{s.sectioncode.to_s.rjust(4, '0')};;RESTOREDATA;NAME:#{(s.name + '*' * 50)[0,50]};DESCRIPTION:#{(s.description + '*' * 100)[0,100]};;" }

	has_many :spaces, foreign_key: :sectioncode_id, primary_key: :sectioncode, dependent: :destroy
	has_many :items, through: :spaces, foreign_key: :sectioncode_id, primary_key: :sectioncode, dependent: :destroy
	def to_param
		sectioncode
	end

	after_commit :create_search_entry, on: :create
	after_commit :update_search_entry, on: :update
	after_commit :destroy_search_entry, on: :destroy

	private
		def create_search_entry
			SearchEntry.create(name: self.name, url: Rails.application.routes.url_helpers.section_path(self.sectioncode), searchable: self)
		end

		def update_search_entry
			if self.search_entry.present?
				self.search_entry.update(name: self.name, url: Rails.application.routes.url_helpers.section_path(self.sectioncode))
			else
				SearchEntry.create(name: self.name, url: Rails.application.routes.url_helpers.section_path(self.sectioncode), searchable: self)
			end
		end

		def destroy_search_entry
			self.search_entry.destroy if self.search_entry.present?
		end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
	before_action :authenticate_user!
	def index
		@sections = Section.all.sort_by(&:sectioncode)
	end
	def show
		@section = Section.find_by!(:sectioncode => params[:sectioncode])
	end

	def new
		@section = Section.new
	end
	
	def create
		@section = Section.new(section_params)

		if @section.save
			redirect_to section_path(@section.sectioncode)
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@section = Section.find_by!(:sectioncode => params[:sectioncode])
		@backpath = section_path(@section.sectioncode)
		@name = @section.name
	end

	def add_to_queue
		# @current_queue
		@section = Section.find_by!(:sectioncode => params[:sectioncode])

		printString = "Section Label for #{@section.name}"
		if @current_queue.print_queue_items.find_by(:itemhash => Digest::SHA256.hexdigest(printString)) != nil
			printItem = @current_queue.print_queue_items.find_by(:itemhash => Digest::SHA256.hexdigest(printString))
			printItem.quantity += 1
			printItem.save!
		else
			printItem = @current_queue.print_queue_items.new(:name => printString, :itemhash => Digest::SHA256.hexdigest(printString), :quantity => 1, :print_content => render("_label", locals: { section: @section }, :layout => false))
			printItem.save!
		end

		

		respond_to do |format|
			format.html
			format.js
		end
	end

	helper_method :add_to_queue
	
	def update
		@section = Section.find_by!(:sectioncode => params[:sectioncode])
		@backpath = section_path(@section.sectioncode)
		@name = @section.name
		if @section.update(section_params)
			redirect_to section_path(@section.sectioncode)
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@section = Section.find_by!(:sectioncode => params[:sectioncode])
		@section.destroy
	
		redirect_to sections_path, status: :see_other
	end

	private
		def section_params
			params.require(:section).permit(:sectioncode, :name, :description)
		end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_with model: @section do |form| %>
     <div class="field">
          <%= form.label :sectioncode, 'Section code' %><br />
          <% @section.errors.full_messages_for(:sectioncode).each do |message| %>
               <div class="destructive"><b><%= message %></b></div>
          <% end %>
          <%= form.number_field :sectioncode %>
     </div>
     <div class="field">
          <%= form.label :name %><br />
          <% @section.errors.full_messages_for(:name).each do |message| %>
               <div class="destructive"><b><%= message %></b></div>
          <% end %>
          <%= form.text_field :name %>
     </div>
     <div class="field">
          <%= form.label :description %><br />
          <% @section.errors.full_messages_for(:description).each do |message| %>
               <div class="destructive"><b><%= message %></b></div>
          <% end %>
          <%= form.text_area :description %>
     </div>
     <div class="actions">
          <%= form.submit %>
     </div>
<% end %>

app/views/sections/edit.html.erb
<%= link_to '< Go back to "'+@section.name+'"', section_path(@section.sectioncode) %>

<h1>Edit <i>"<%= @section.name %>"</i></h1>

<%= render "form", section: @section %>

app/views/sections/index.html.erb
<h1>Storage</h1>

<h2>Assigned Sections</h2>

<p>Use sections to group storage spaces that are physically close to each other.</p>

<% if @sections.empty? %>
<p>You have not created any sections yet. </p>
<% else %>
<table class="standard-table">
<tr>
    <th>Code</th>
    <th>Name</th> 
    <th>Description</th>
</tr>
<% @sections.each do |section| %>
     <tr>
          <td><%= section.sectioncode %></td>
          <td><%= link_to section.name, section_path(section.sectioncode) %></td> 
          <td><%= section.description %></td>
     </tr>
<% end %>
</table>
<% end %>
<i><%= link_to "Create a new section", new_section_path %></i>

app/views/sections/new.html.erb
<%= link_to '< See all sections', sections_path %>

<h1>Create a New Section</h1>

<%= render "form", section: @section %>

app/views/sections/show.html.erb
<%= link_to '< See all sections', sections_path %>

<h1><%= @section.name %></h1>

<%= render "label", section: @section %>

<table class="open-table">
<tr>
     <th>Parameter</th><th>Value</th>
</tr>
<tr><td><i>Section Code</i></td><td><%= @section.sectioncode %></td></tr>
<tr><td><i>Name</i></td><td><%= @section.name %></td></tr>
<tr><td><i>Description</i></td><td><%= @section.description %></td></tr>
<tr><td><i>Created at</i></td><td><%= @section.created_at %></td></tr>
<tr><td><i>Last updated at</i></td><td><%= @section.updated_at %></td></tr>

</table>
<i><%= link_to "Edit", edit_section_path %></i> | <i><%= link_to "View Spaces >", section_spaces_path(@section.sectioncode) %></i>

<%= button_to "Add to print queue", add_to_queue_section_path(@section.sectioncode) %>

<h2 class="destructive">Delete this section</h2>
<p>If you no longer use this section, you can choose to delete it. All spaces associated with this section will be destroyed. This action is irreversible.</p>

<%= button_to "I understand the consequences, delete this section", section_path(@section.sectioncode), data: { turbo_confirm: "Are you sure you want to delete this section?\n\n This action is irreversible." }, method: :delete, class: "destructive-background" %>