config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	resources :sections, param: :sectioncode do
		get "/sections", to: "sections#index"
		member do
			post :add_to_queue
		end
		resources :spaces, param: :spacecode do
			member do
				post :add_to_queue
			end
			resources :items, param: :itemcode do
				post :add_small_to_queue
				post :add_large_to_queue
			end
		end
	end

	get "/print", to: "print#index"

	resources :print_queue_items, only: [] do
		member do
			post :change_quantity
			delete :delete_item
		end
	end

	get 'print_shop', to: "print_shop#index" 
	get 'print_page', to: "print_shop#show" 
	get 'search', to: "search#index" 

	# Defines the root path route ("/")
	root :controller => 'static', :action => :index
end

app/models/item.rb
require 'barby/barcode/ean_13'

class Item < ApplicationRecord
	include HasBarcode
	include Searchable

	validates :itemcode,  allow_blank: false, presence: true, uniqueness: { scope: :spacecode_actual_id }
	validates_numericality_of :itemcode, :less_than_or_equal_to => 9999, :greater_than_or_equal_to => 1

		validates :name, length: {maximum: 50}, allow_blank: false, presence: true
	validates :description, length: {maximum: 100}, allow_blank: false, presence: true
		validates :quantity,  allow_blank: false, presence: true
	validates_numericality_of :quantity, :greater_than_or_equal_to => 1

	has_barcode :barcode,
				:outputter => :svg,
				:type => Barby::EAN13,
				:value => Proc.new { |s| "#{s.sectioncode_id.to_s.rjust(4, '0')}#{Space.find_by(id: s.spacecode_actual_id).spacecode.to_s.rjust(4, '0')}#{s.itemcode.to_s.rjust(4, '0')}" }

	belongs_to :space, foreign_key: :spacecode_actual_id, primary_key: :id, required: true

	after_commit :create_search_entry, on: :create
	after_commit :update_search_entry, on: :update
	after_commit :destroy_search_entry, on: :destroy

	private
		def create_search_entry
			SearchEntry.create(name: self.name, url: Rails.application.routes.url_helpers.section_space_item_path(self.sectioncode_id, Space.find_by!(:id=>self.spacecode_actual_id).spacecode, self.itemcode), searchable: self)
		end

		def update_search_entry
			if self.search_entry.present?
				self.search_entry.update(name: self.name, url: Rails.application.routes.url_helpers.section_space_item_path(self.sectioncode_id, Space.find_by!(:id=>self.spacecode_actual_id).spacecode, self.itemcode))
			else
				SearchEntry.create(name: self.name, url: Rails.application.routes.url_helpers.section_space_item_path(self.sectioncode_id, Space.find_by!(:id=>self.spacecode_actual_id).spacecode, self.itemcode), searchable: self)
			end
		end

		def destroy_search_entry
			self.search_entry.destroy if self.search_entry.present?
		end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :authenticate_user!
	def index
		@space = Space.find_by!(:sectioncode_id => params[:section_sectioncode], :spacecode => params[:space_spacecode])
		@items = @space.items
	end
	def show
		@section = Section.find_by!(:sectioncode => params[:section_sectioncode])
		@space = Space.find_by!(:sectioncode_id => params[:section_sectioncode], :spacecode => params[:space_spacecode])
		@item = Item.find_by!(:sectioncode_id => params[:section_sectioncode], :spacecode_actual_id => @space.id, :itemcode=>params[:itemcode])
	end

	def new
		@section = Section.find_by!(:sectioncode => params[:section_sectioncode])
		@space = Space.find_by!(:spacecode=>params[:space_spacecode], :sectioncode_id => params[:section_sectioncode])
		@item = Item.new
	end
	
	def create
		@section = Section.find_by!(:sectioncode => params[:section_sectioncode])
		@space = Space.find_by!(:spacecode=>params[:space_spacecode], :sectioncode_id => params[:section_sectioncode])
		@item = Item.new(item_params)
		@item.spacecode_actual_id = @space.id
		@item.sectioncode_id = @section.sectioncode
		if @item.save
			redirect_to section_space_item_path(@space.sectioncode_id, @space.spacecode, @item.itemcode)
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@section = Section.find_by!(:sectioncode => params[:section_sectioncode])
		@space = Space.find_by!(:spacecode=>params[:space_spacecode], :sectioncode_id => params[:section_sectioncode])
		@item = Item.find_by!(:sectioncode_id => params[:section_sectioncode], :spacecode_actual_id => @space.id, :itemcode=>params[:itemcode])
		@backpath = section_space_item_path(@item.sectioncode_id, @space.spacecode, @item.itemcode)
		@name = @item.name
	end


	def add_large_to_queue
		@item = Item.find_by!(:sectioncode_id => params[:section_sectioncode], :spacecode_actual_id => @space.id, :itemcode => params[:item_itemcode])

		printString = "Large Item Label for #{@item.name}"
		if @current_queue.print_queue_items.find_by(:itemhash => Digest::SHA256.hexdigest(printString)) != nil
			printItem = @current_queue.print_queue_items.find_by(:itemhash => Digest::SHA256.hexdigest(printString))
			printItem.quantity += 1
			printItem.print_content = render("_label", locals: { item: @item }, :layout => false)
			printItem.save!
		else
			printItem = @current_queue.print_queue_items.new(:name => printString, :itemhash => Digest::SHA256.hexdigest(printString), :quantity => 1, :print_content => render("_label", locals: { item: @item }, :layout => false))
			printItem.save!
		end

		respond_to do |format|
			format.html
			format.js
		end
	end
	helper_method :add_large_to_queue

	def add_small_to_queue
		puts params
		@item = Item.find_by!(:sectioncode_id => params[:section_sectioncode], :spacecode_actual_id => @space.id, :itemcode => params[:item_itemcode])
		
		printString = "Small Item Label for #{@item.name}"
		if @current_queue.print_queue_items.find_by(:itemhash => Digest::SHA256.hexdigest(printString)) != nil
			printItem = @current_queue.print_queue_items.find_by(:itemhash => Digest::SHA256.hexdigest(printString))
			printItem.quantity += 1
			printItem.print_content = render("_labelsmall", locals: { item: @item }, :layout => false)
			printItem.save!
		else
			printItem = @current_queue.print_queue_items.new(:name => printString, :itemhash => Digest::SHA256.hexdigest(printString), :quantity => 1, :print_content => render("_labelsmall", locals: { item: @item }, :layout => false))
			printItem.save!
		end


		respond_to do |format|
			format.html
			format.js
		end
	end
	helper_method :add_small_to_queue

	
	def update
		@section = Section.find_by!(:sectioncode => params[:section_sectioncode])
		@space = Space.find_by!(:spacecode=>params[:space_spacecode], :sectioncode_id => params[:section_sectioncode])
		@item = Item.find_by!(:sectioncode_id => params[:section_sectioncode], :spacecode_actual_id => @space.id, :itemcode=>params[:itemcode])
		@backpath = section_space_item_path(@item.sectioncode_id, @space.spacecode, @item.itemcode)
		@name = @item.name
		
		if @item.update(item_params)
			redirect_to section_space_item_path(@space.sectioncode_id, @space.spacecode, @item.itemcode)
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@item = Item.find_by!(:sectioncode_id => params[:section_sectioncode], :spacecode_actual_id => @space.id, :itemcode=>params[:itemcode])
		@item.destroy
	
		redirect_to section_space_items_path, status: :see_other
	end

	private
		def item_params
			params.require(:item).permit(:itemcode, :name, :description, :quantity)
		end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: @item, url: [@section, @space, @item]) do |form| %>
     <div class="field">
          <%= form.label :itemcode, 'Item code' %><br />
          <% @item.errors.full_messages_for(:itemcode).each do |message| %>
               <div class="destructive"><b><%= message %></b></div>
          <% end %>
          <%= form.number_field :itemcode %>
     </div>
     <div class="field">
          <%= form.label :name %><br />
          <% @item.errors.full_messages_for(:name).each do |message| %>
               <div class="destructive"><b><%= message %></b></div>
          <% end %>
          <%= form.text_field :name %>
     </div>
     <div class="field">
          <%= form.label :description %><br />
          <% @item.errors.full_messages_for(:description).each do |message| %>
               <div class="destructive"><b><%= message %></b></div>
          <% end %>
          <%= form.text_area :description %>
     </div>
     <div class="field">
          <%= form.label :quantity %><br />
          <% @item.errors.full_messages_for(:quantity).each do |message| %>
               <div class="destructive"><b><%= message %></b></div>
          <% end %>
          <%= form.number_field :quantity %>
     </div>
     <div class="actions">
          <%= form.submit %>
     </div>
<% end %>

app/views/items/edit.html.erb
<%= link_to '< Go back to "'+@name+'"', @backpath %>

<h1>Edit <i>"<%= @name %>"</i></h1>

<%= render "form", section: @section, space: @space, item: @item %>

app/views/items/index.html.erb
<%= link_to '< Go back to "'+@space.name+'"', section_space_path(:spacecode => @space.spacecode) %>

<h1>Items</h1>
<h2>Assigned Items</h2>

<% if @items.empty? %>
<p>You have not added any items to <i>"<%= @space.name %>"</i> yet. </p>
<% else %>
<table class="standard-table">
<tr>
    <th>Code</th>
    <th>Name</th> 
    <th>Description</th>
    <th>Quantity</th>
</tr>
<% @items.each do |item| %>
     <tr>
          <td><%= item.itemcode %></td>
          <td><%= link_to item.name, section_space_item_path(:itemcode=>item.itemcode) %></td> 
          <td><%= item.description %></td>
          <td><%= item.quantity %></td>
     </tr>
<% end %>
</table>
<% end %>
<i><%= link_to "Add an item", new_section_space_item_path %></i>

app/views/items/new.html.erb
<%= link_to '< See all items', section_space_items_path %>

<h1>Add an Item</h1>

<%= render "form", section: @section, space: @space, item: @item %>

app/views/items/show.html.erb
<%= link_to '< See all items', section_space_items_path %>

<h1><%= @item.name %></h1>

<%= render "label", item: @item %>
<%= render "labelsmall", item: @item %>

<table class="open-table">
<tr>
     <th>Parameter</th><th>Value</th>
</tr>
<tr><td><i>Item Code</i></td><td><%= @item.itemcode %></td></tr>
<tr><td><i>Name</i></td><td><%= @item.name %></td></tr>
<tr><td><i>Description</i></td><td><%= @item.description %></td></tr>
<tr><td><i>Quantity</i></td><td><%= @item.quantity %></td></tr>
<tr><td><i>Created at</i></td><td><%= @item.created_at %></td></tr>
<tr><td><i>Last updated at</i></td><td><%= @item.updated_at %></td></tr>

</table>
<i><%= link_to "Edit", edit_section_space_item_path %></i>


<%= button_to "Add small label to print queue", section_space_item_add_small_to_queue_path(@section.sectioncode, @space.spacecode, @item.itemcode) %>

<%= button_to "Add large label to print queue", section_space_item_add_large_to_queue_path(@section.sectioncode, @space.spacecode, @item.itemcode) %>

<h2 class="destructive">Delete this Item</h2>
<p>This action is irreversible.</p>
<%= button_to "I understand the consequences, delete this item", section_space_item_path, data: { turbo_confirm: "Are you sure you want to delete this space?\n\n This action is irreversible." }, method: :delete, class: "destructive-background" %>