config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

	resources :sections, param: :sectioncode do
		get "/sections", to: "sections#index"
		member do
			post :add_to_queue
		end
		resources :spaces, param: :spacecode do
			member do
				post :add_to_queue
			end
			resources :items, param: :itemcode do
				post :add_small_to_queue
				post :add_large_to_queue
			end
		end
	end

	get "/print", to: "print#index"

	resources :print_queue_items, only: [] do
		member do
			post :change_quantity
			delete :delete_item
		end
	end

	get 'print_shop', to: "print_shop#index" 
	get 'print_page', to: "print_shop#show" 
	get 'search', to: "search#index" 

	# Defines the root path route ("/")
	root :controller => 'static', :action => :index
end

app/controllers/print_controller.rb
class PrintController < ApplicationController
	before_action :authenticate_user!
	
	def index
		@queue = @current_queue
	end

	def change_quantity
		@queue = @current_queue
		puts params[:id], params[:quantity]
		
		respond_to do |format|
			format.html
			format.js
		end
	end
	helper_method :change_quantity

	def destroy
		@queue = @current_queue
		@queue.destroy
		session[:print_queue_id] = nil
		redirect_to root_path
	end
end

app/helpers/print_helper.rb
module PrintHelper
end

app/views/print/index.html.erb
<h1>Print</h1>

<% if @queue.print_queue_items.empty? %>
     <p>No items in print queue. </p>
<% else %>
     <table class="standard-table">
          <tr>
               <th>Item</th>
               <th>Name</th>
               <th>Quantity</th>
               <th>Delete</th>
          </tr>
          <% @queue.print_queue_items.each do |item| %>
               <tr>
                    <td><%= item.print_content.html_safe %></td>
                    <td><b><%= item.name %></b></td>
                    <td>
                         <%= form_with url: change_quantity_print_queue_item_path(item), method: :post do |form| %>
                              <%= form.number_field :quantity,  min: 1, value:item.quantity, onchange: "this.form.submit()"%>
                         <% end %>
                    </td>
                    <td>
                    <%= button_to "Delete", delete_item_print_queue_item_path(item), data: { turbo_confirm: "Are you sure you want to delete this item?\n\n You can add this item again from the item's inventory page." }, method: :delete, class: "destructive-background" %>

                    </td>
               </tr>
          <% end %>
     </table>
     <%= link_to "Go to Print Shop", print_shop_path %>
<% end %>